### ISSUE TITLE
GS308EPP (double P) support?

### ISSUE THREAD

**Issue by vanrace** [ckarrie/ha-netgear-plus#31] opened 2024-10-16 20:13 UTC
I just received my GS308EPP. I think the only difference with the supported GS308EP model is the extra power budget, but I could be wrong. It is not in the supported models list, maybe just because there was no one to test? 

----------------------
EDIT: 

I tried to use it anyway of course, when trying to set up the integration I received an 'Unknown errror occurred'. 

Then, not bothered by any Python- but with some outdated programming knowledge I added a new configuration based on the EP version to the models.py file and added it to the models array and lo and behold, it works! 

Let me post the file contents below. Not a GIT user, sorry.... Maybe you could integrate the change if the review turns out okay? THANKS!!

BTW: Happy to do more testing if needed. I am on fw version V1.0.1.4

**Comment by vanrace** [comment] 2024-10-16 20:44
Adapted models.py:

`"""Definitions of auto-detectable Switch models."""


class AutodetectedSwitchModel:
    ALLOWED_COOKIE_TYPES = ["SID"]
    MODEL_NAME = None
    PORTS = None
    POE_PORTS = []
    POE_MAX_POWER_ALL_PORTS = None
    POE_MAX_POWER_SINGLE_PORT = None
    POE_SCHEDULING = False
    CHECKS_AND_RESULTS = []

    AUTODETECT_TEMPLATES = [
        { "method": "get",
          "url": "http://{ip}/login.cgi" },
        { "method": "get",
          "url": "http://{ip}/login.htm" },
        { "method": "get",
          "url": "http://{ip}/" },
    ]

    LOGIN_TEMPLATE = { "method": "post",
                       "url": "http://{ip}/login.cgi",
                        "key": "password" }

    SWITCH_INFO_TEMPLATES = [
        { "method": "get",
          "url": "http://{ip}/switch_info.htm" },
        { "method": "get",
          "url": "http://{ip}/switch_info.cgi" }
    ]
    PORT_STATISTICS_TEMPLATES = [
        { "method": "post",
          "url": "http://{ip}/portStatistics.cgi" }
    ]
    PORT_STATUS_TEMPLATES = [
        { "method": "post",
          "url": "http://{ip}/status.htm" }
    ]
    POE_PORT_CONFIG_TEMPLATES = [

    ]
    LOGOUT_TEMPLATES = [
        { "method": "post",
          "url": "http://{ip}/logout.cgi" }
    ]


    def __init__(self) -> None:
        pass

    def get_autodetect_funcs(self):
        return self.CHECKS_AND_RESULTS


class GS105E(AutodetectedSwitchModel):
    MODEL_NAME = "GS105E"
    PORTS = 5
    CHECKS_AND_RESULTS = [
        ("check_login_form_rand", [True]),
        ("check_login_title_tag", ["GS105E"]),
    ]


class GS105Ev2(AutodetectedSwitchModel):
    MODEL_NAME = "GS105Ev2"
    PORTS = 5
    CHECKS_AND_RESULTS = [
        ("check_login_form_rand", [True]),
        ("check_login_title_tag", ["GS105Ev2"]),
    ]


class GS108E(AutodetectedSwitchModel):
    MODEL_NAME = "GS108E"
    PORTS = 8
    CHECKS_AND_RESULTS = [
        ("check_login_form_rand", [True]),
        ("check_login_title_tag", ["GS108E"]),
        (
            "check_login_switchinfo_tag",
            ["GS308E - 8-Port Gigabit Ethernet Smart Managed Plus Switch"],
        ),
    ]
    ALLOWED_COOKIE_TYPES = ["GS108SID", "SID"]


class GS108Ev3(AutodetectedSwitchModel):
    MODEL_NAME = "GS108Ev3"
    PORTS = 8
    CHECKS_AND_RESULTS = [
        ("check_login_form_rand", [True]),
        ("check_login_title_tag", ["GS108Ev3"]),
        (
            "check_login_switchinfo_tag",
            [
                "GS108Ev3 - 8-Port Gigabit ProSAFE Plus Switch",
                "GS108Ev3 - 8-Port Gigabit Ethernet Smart Managed Plus Switch",
            ],
        ),
    ]
    ALLOWED_COOKIE_TYPES = ["GS108SID", "SID"]


class GS3xxSeries(AutodetectedSwitchModel):
    SWITCH_INFO_TEMPLATES = [
        { "method": "get",
          "url": "http://{ip}/dashboard.cgi" }
    ]
    PORT_STATISTICS_TEMPLATES = [
        { "method": "get",
          "url": "http://{ip}/portStatistics.cgi" }
    ]
    POE_PORT_CONFIG_TEMPLATES = [
        { "method": "get",
          "url": "http://{ip}/PoEPortConfig.cgi" }
    ]
    POE_PORT_STATUS_TEMPLATES = [
        { "method": "get",
          "url": "http://{ip}/getPoePortStatus.cgi" }
    ]


class GS305EP(GS3xxSeries):
    MODEL_NAME = "GS305EP"
    PORTS = 5
    POE_PORTS = [1, 2, 3, 4]
    POE_MAX_POWER_ALL_PORTS = 63
    CHECKS_AND_RESULTS = [
        ("check_login_form_rand", [True]),
        ("check_login_title_tag", ["GS305EP"]),
    ]


class GS308EP(GS3xxSeries):
    MODEL_NAME = "GS308EP"
    PORTS = 8
    POE_PORTS = [1, 2, 3, 4, 5, 6, 7, 8]
    POE_MAX_POWER_ALL_PORTS = 62
    CHECKS_AND_RESULTS = [
        ("check_login_form_rand", [True]),
        ("check_login_title_tag", ["GS308EP"]),
    ]

class GS308EPP(GS3xxSeries):
    MODEL_NAME = "GS308EPP"
    PORTS = 8
    POE_PORTS = [1, 2, 3, 4, 5, 6, 7, 8]
    POE_MAX_POWER_ALL_PORTS = 123
    CHECKS_AND_RESULTS = [
        ("check_login_form_rand", [True]),
        ("check_login_title_tag", ["GS308EPP"]),
    ]


class GS316EP(GS3xxSeries):
    MODEL_NAME = "GS316EP"
    PORTS = 16
    POE_PORTS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
    POE_MAX_POWER_ALL_PORTS = 180
    POE_MAX_POWER_SINGLE_PORT = 30
    POE_SCHEDULING = True
    CHECKS_AND_RESULTS = [
        ("check_login_form_rand", [True]),
        ("check_login_title_tag", ["GS316EP"]),
    ]
    LOGIN_TEMPLATE = { "method": "post",
                       "url": "http://{ip}/homepage.html",
                       "key": "LoginPassword" }
    ALLOWED_COOKIE_TYPES = ["gambitCookie"]


class GS316EPP(GS316EP):
    MODEL_NAME = "GS316EPP"
    POE_POWER_ALL_PORTS = 231
    CHECKS_AND_RESULTS = [
        ("check_login_form_rand", [True]),
        ("check_login_title_tag", ["GS316EPP"]),
    ]


MODELS = [
    GS105E,
    GS105Ev2,
    GS108E,
    GS108Ev3,
    GS305EP,
    GS308EP,
    GS308EPP,
    GS316EP,
    GS316EPP,
]
`

**Comment by loso2255** [comment] 2024-10-17 10:15
+1

**Comment by foxey** [comment] 2024-10-18 19:57
@vanrace It's probably just a matter of adding the identification to the models.py file, but do me a favor and share the debug output for the integration with me.

**Comment by vanrace** [comment] 2024-10-18 20:50
@foxey , thanks for answering. , please read the rest of the post, I added it myself to the models.py and it works now, i shared the changes I did, just not sure how to add it to the repository. Hope you can help there! Thanks for all your work!!

**Comment by foxey** [comment] 2024-10-19 08:12
@vanrace I missed that. Thanks for pointing it out. Ideally, you'd create a pull request, but since these changes are so minor, let me add them to the next release (unless you want to learn git 🙂)

**Comment by vanrace** [comment] 2024-10-19 08:32
Maybe I will give it a try, I’ll keep you updated.

**Comment by loso2255** [comment] 2024-10-19 12:25
i can confirm, at least for me, that is working fine for me

**Comment by vanrace** [comment] 2024-10-19 16:19
@loso2255 : nice! Here it works as well although I did not test the power control since I only have some stuff on it I don’t like to power cycle at the moment (like my HomeAssistant rpi )

thanks for the quick action! i appreciate it

**Comment by foxey** [comment] 2024-10-19 17:12
Good to hear! BTW you can also power cycle an empty port (if you still have one), but apart from the logging, you won't have evidence that it really works. I'll close this issue for now. Please reopen it if you discover something is not working as expected.

**Closed by foxey** 2024-10-19 17:12 UTC

**Comment by vanrace** [comment] 2024-10-21 19:24
Tested power cycle in the meantime: works!
